const START_POMODOROS_FETCH = "START_POMODOROS_FETCH";
const FINISH_POMODOROS_FETCH = "FINISH_POMODOROS_FETCH";

const ACTION_TYPES = {
	START_POMODOROS_FETCH,
	FINISH_POMODOROS_FETCH,
};

export default ACTION_TYPES;
