const START_POMODOROS_FETCH_GET = "START_POMODOROS_FETCH_GET";
const FINISH_POMODOROS_FETCH_GET = "FINISH_POMODOROS_FETCH_GET";
const START_POMODOROS__FETCH_POST = "START_POMODOROS_FETCH_POST";
const FINISH_POMODOROS_FETCH_POST = "FINISH_POMODOROS_FETCH_POST";
const SELECT_MAIN_SCREEN = "SELECT_MAIN_SCREEN";

const ACTION_TYPES = {
	START_POMODOROS_FETCH_GET,
	FINISH_POMODOROS_FETCH_GET,
	START_POMODOROS__FETCH_POST,
	FINISH_POMODOROS_FETCH_POST,
	SELECT_MAIN_SCREEN,
};

export default ACTION_TYPES;
